name: Hexo Deploy Automatically (with cache and yarn)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Restore Project Cache
        id: project-cache
        uses: actions/cache@v4
        with:
          path: luckyship.github.io
          key: hexo-project-cache

      - name: Clone Project (if cache miss)
        if: steps.project-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/luckyship/luckyship.github.io.git

      - name: pull Project ()
        run: |
          cd luckyship.github.io
          git checkout dev
          git pull
          git submodule update --init --recursive
          git submodule update --remote --merge

      - name: Save Project to Cache
        if: steps.project-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: luckyship.github.io
          key: hexo-project-cache

      # Node.js + Yarn
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: luckyship.github.io/yarn.lock

      # 安装依赖
      - name: Install Dependencies with Yarn
        run: |
          cd luckyship.github.io
          yarn install --frozen-lockfile

      # 部署
      - name: Deploy Hexo Blog
        env:
          SSH_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        run: |
          cd luckyship.github.io
          export TZ='Asia/Shanghai' 

          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name 'luckyship'
          git config --global user.email '304093931@qq.com'

          yarn deploy
