name: Deploy Hexo Blog

on:
  push:
    branches:
      - dev # 或 master，根据你仓库的主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码 + 子模块
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive # 初始化所有子模块
          fetch-depth: 0 # 保留完整 git 历史（可选）

      # 2. 缓存 node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 更新 submodule（强制拉最新远程）
      - name: Update submodules from remote
        run: git submodule update --remote --init

      # 5. 构建 Hexo
      - name: Generate site
        run: npm run deploy

      # 6. 可选：部署到 GitHub Pages / FTP 等
      # - name: Deploy
      #   run: npx hexo deploy
